Repository bringmetheaugust/Memory-Storm-2, pull requests merged in 2020-10, with the labels that each got.

#10 Random cards
  src/actionCreators/cards.js
  src/actionCreators/gameState.js
  src/actionCreators/saga.js
  src/components/GameField.jsx
  src/components/preloader.jsx
  src/constants/actionTypes.js
  src/constants/gameSettings.js
  src/media/cards/card_1.jpg
  src/media/cards/card_10.jpg
  src/media/cards/card_11.png
  src/media/cards/card_12.jpeg
  src/media/cards/card_13.jpg
  src/media/cards/card_14.png
  src/media/cards/card_15.jpg
  src/media/cards/card_16.jpg
  src/media/cards/card_17.png
  src/media/cards/card_18.png
  src/media/cards/card_2.jpeg
  src/media/cards/card_3.png
  src/media/cards/card_4.jpeg
  src/media/cards/card_5.jpg
  src/media/cards/card_6.jpg
  src/media/cards/card_7.jpg
  src/media/cards/card_8.jpg
  src/media/cards/card_9.jpg
  src/media/cards/index.ts
  src/reducer/index.js
  src/reducer/initialState.js
  src/style/game-field/index.sass
  src/style/index.sass
  src/style/preloader.sass
Labels: enhancement

#11 Rebuild
  src/components/Alert.jsx
  src/components/Counter.jsx
  src/components/GameField.jsx
  src/style/game-field/count.sass
  src/style/game-field/index.sass
  src/style/index.sass
Labels: bug, enhancement

#13 README.md: fix URL test realm for project
  README.md
Labels: bug, invalid
